name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Checkout Code
        uses: actions/checkout@v4

      - name: 🪜 Install Pnpm
        uses: pnpm/action-setup@v4

      - name: 🖥️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: 🏗️ Install Deps
        run: pnpm i

      - name: 📦 Build Package
        run: pnpm run build

      - name: 🛠️ Lint Fix
        run: pnpm run lint:fix
